### ISSUE TITLE
Need a picture of some learning at Coffee && Code

### ISSUE THREAD

**Issue by chipbuster** [UCMercedACM/Website-Theme#18]
This one shouldn't be hard. For slider 3 on the main page, we're still using the stock image of a robot octo-elephant or whatever it is. Find or take a high-quality photo of someone doing some learning at a Coffee && Code, then add it to the repo and place that image onto the slide.

(Note, you will probably want to take a portrait (vertical) photo if you want to avoid upsetting the layout)

**Comment by SmilingEyes** [comment]
I'll be bringing my DSLR camera for C&&C this Friday (April 24) and hopefully I can get a great picture to replace the octopus robot

**Comment by chipbuster** [comment]
Thanks for finally fixing that!

For future reference, it's helpful to close issues with a commit-hash (or series of commit hashes) from where the issue was fixed. You can find the commit hash by using `git log` or by navigating to the commit in the web interface. If you're looking at the list of commits, there's even a button to copy the commit hash. Github is even smart enough to condense the hash and create a link to the commit, in case anyone wants to examine it in the future.

This issue was fixed at commit 84f3184ea35024817eae1ae0b8b9872ba1fe4654, also known as "Oh god, he has no eyes."
