### ISSUE TITLE
Navbar text too low

### ISSUE THREAD

**Issue by chipbuster** [UCMercedACM/Website-Theme#19]
THE TEXT IS TOO LOW.
![screenshot - 230115 - 14 23 06](https://cloud.githubusercontent.com/assets/4605384/5883886/612bfa98-a30b-11e4-93ea-80725bddf47f.png)

SEE? ITS TOO LOW.

FIX IT

**Comment by rleewang** [comment]
Fixed as of c4d226412fb04678d6a2fd9495de1a54ebed06a2
